package org.example.compilador;

public enum TipodeToken {
    // Identificadores
    IDENTIFICADOR, NUMB, STRING, CARACTERE, FLOAT, BOOLEAN, NULL, VIRGULA, PONTO,


    //DELIMITADORES
    PARENTESE_ABRINDO, PARENTESE_FECHANDO, COLCHETE_ABRINDO, COLCHETE_FECHANDO, CHAVES_ABRINDO, CHAVES_FECHANDO,
    PONTO_VIRGULA, ABRE_ASPAS, FECHA_ASPAS,

    //palavra reservada

    PALAVRA_RESERVADA,

    //Operadores aritmeticos
    OPERADOR_ARITIMETICO_SOMA, OPERADOR_ARITIMETICO_MULTIPLICACAO, OPERADOR_ARITMETICO_SUBTRACAO,
    OPERADOR_ARITMETICO_DIVISAO, OPERADOR_ARITIMETICO_RESTO,  OPERADOR_ARITIMETICO_INCREMENTO,
    OPERADOR_ARITIMETICO_DECREMENTO, OPERADOR_CONCATENACAO,

    //OPERADOR DE ATRIBUIÇÃO
    IGUAL_ATRIBUICAO, SOMA_ATRIBUICAO, SUBTRACAO_ATRIBUICAO, MULTIPLICACAO_ATRIBUICAO, DIVISAO_ATRIBUICAO,

    //OPERADORES RELACIONAIS
    IGUAL_A, MAIORQUE, MENORQUE, MAIORQUE_IGUAL, MENORQUE_IGUAL,

    //Operadores Lógicos
    E, OU, DIFERENTE,

    //OPERADORES BIT A BIT
    E_BIT, XOR_BIT, OU_BIT, NAO,

    //OPERADOR TERNARIO
    INTERROGACAO, DOIS_PONTOS,

    //OPERADORES DE INSTANCIA
    INSTANCEOF,

    //COMENTARIOS
    BARRA_BARRA, BARRA_ASTERISCO, ASTERISCO_BARRA, BARRA_ASTERISCO_ASTERISCO,
}
