package org.example.compilador;

public enum TipodeToken {
    // Identificadores e literais
    IDENTIFICADOR, NUMB, STRING, CARACTERE, PARENTESE_ABRINDO, PARENTESE_FECHANDO, COLCHETE_ABRINDO, COLCHETE_FECHANDO, CHAVES_ABRINDO, CHAVES_FECHANDO,
    PONTO_VIRGULA, IGUAL, VIRGULA, PONTO, ATRIBUICAO,
    CONCATENACAO, DOIS_PONTOS,

    //palavra reservada

    PALAVRA_RESERVADA,

    //Operadores aritmeticos
    OPERADOR_ARITIMETICO_SOMA, OPERADOR_ARITIMETICO_MULTIPLICACAO, OPERADOR_ARITMETICO_SUBTRACAO,
    OPERADOR_ARITMETICO_DIVISAO, OPERADOR_ARITMETICO_RESTO, OPERADOR_ARITMETICO_EXPOENTE, OPERADOR_ARITMETICO_INCREMENTO, OPERADOR_ARITMETICO_DECREMENTO,
}
