package org.example.compilador;

public enum TipodeToken {
    // Identificadores
    IDENTIFICADOR, NUMB, STRING, CARACTERE, FLOAT, BOOLEAN, NULL, VIRGULA, PONTO, ATRIBUICAO,
    CONCATENACAO,

    //DELIMITADORES
    PARENTESE_ABRINDO, PARENTESE_FECHANDO, COLCHETE_ABRINDO, COLCHETE_FECHANDO, CHAVES_ABRINDO, CHAVES_FECHANDO,
    PONTO_VIRGULA,

    //palavra reservada

    PALAVRA_RESERVADA,

    //Operadores aritmeticos
    OPERADOR_ARITIMETICO_SOMA, OPERADOR_ARITIMETICO_MULTIPLICACAO, OPERADOR_ARITMETICO_SUBTRACAO,
    OPERADOR_ARITMETICO_DIVISAO, OPERADOR_ARITIMETICO_RESTO, OPERADOR_ARITIMETICO_EXPOENTE, OPERADOR_ARITIMETICO_INCREMENTO,
    OPERADOR_ARITIMETICO_DECREMENTO,

    //OPERADOR DE ATRIBUIÇÃO
    IGUAL, SOMA_IGUAL, SUBTRACAO_IGUAL, MULTIPLICACAO_IGUAL, DIVISAO_IGUAL,

    //OPERADORES RELACIONAIS
    IGUAL_IGUAL, DIFERENTE_IGUAL, MAIORQUE, MENORQUE, MAIORQUE_IGUAL, MENORQUE_IGUAL,

    //Operadores Lógicos
    E, OU, DIFERENTE,

    //OPERADORES BIT A BIT
    EBIT, OU_EXCLUSIVO, OU_INCLUSIVO, NAO, OPERADOR_DESLOC_DIREITA_COMSINAL, OPERADOR_DESLOC_DIREITA_SEMSINAL, OPERADOR_DESLOC_ESQUERDA,

    //OPERADOR TERNARIO
    INTERROGACAO, DOIS_PONTOS,

    //OPERADORES DE INSTANCIA
    INSTANCEOF,

    //COMENTARIOS
    BARRA_BARRA, BARRA_ASTERISCO, ASTERISCO_BARRA, BARRA_ASTERISCO_ASTERISCO,
}
